name: Create and publish a Docker image.
env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}

on: 
  push:
    branches: 
      - "main"
      - "master"

  pull_request:
    branches:
      - "main"
      - "master"
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List current directory
        run: ls -la

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: mlflow
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            GITHUB_REPOSITORY=${{ github.repository }}
            GITHUB_SHA=${{ github.sha }}
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gilsamamlflow'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6df782e285cf4bb0b5d3dcafc7883458 }}
          images: 'ghcr.io//${{ secrets.AzureAppService_ContainerUsername_489bb7cd30534bd28eeef360c4a0eb0e }}/manuelgilm/mlflowcloud:${{ github.sha }}'